name: Test Deployment
on:
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: Set to 'true' to deploy to production
        default: "false"
        required: false

jobs:
  reftest:
    name: Ref test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
