name: Test Deployment
on:
  push:
    branches:
      - "main"
      - "release/*"
      - "feature/*"
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: Set to 'true' to deploy to production
        default: "false"
        required: false

jobs:
  reftest:
    name: Ref test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: select workspace
        run: |
          workspace="dev"      
          if [[ ${{github.ref}} == "refs/heads/main" ]]; then 
            workspace="staging"
          elif [[ "${{github.event.inputs.deploy_to_production}}" == "true" && ${{github.ref}} =~ "refs/heads/release/*" ]]; then
            workspace="production"
          fi
          echo $workspace
          echo "::set-output name=workspace::${workspace}"
